// maps common country names (lowercase) to Adzuna country codes
export const countryMap = {
  "uk": "gb",
  "united kingdom": "gb",
  "england": "gb",
  "britain": "gb",
  "gb": "gb",
  "usa": "us",
  "us": "us",
  "united states": "us",
  "america": "us",
  "germany": "de",
  "deutschland": "de",
  "de": "de",
  "france": "fr",
  "fr": "fr",
  "australia": "au",
  "au": "au",
  "canada": "ca",
  "ca": "ca",
  "india": "in",
  "in": "in",
  "netherlands": "nl",
  "nl": "nl",
  "united arab emirates": "ae",
  "uae": "ae",
  "dubai": "ae",
  "egypt": "eg", // not officially supported by Adzuna in many cases, but kept for parsing
};
